apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eShopOnWeb
  annotations:
    github.com/project-slug: leandrofrs/eShopOnWeb
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: guests
